#!/bin/bash

echo "🔥 Firebase Environment Variables Setup"
echo "======================================"
echo ""
echo "You need to add these environment variables to your Railway project:"
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Click on 'Variables' tab"
echo "3. Add the following variables:"
echo ""

# Read the service account file and extract values
if [ -f "services/firebase_service_account.json" ]; then
    echo "FIREBASE_PROJECT_ID=nutricious4u-63158"
    echo "FIREBASE_PRIVATE_KEY_ID=12ef6bab2ae0ca218c25477e6702e412626c10ff"
    echo "FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@nutricious4u-63158.iam.gserviceaccount.com"
    echo "FIREBASE_CLIENT_ID=110249587534948017563"
    echo "FIREBASE_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40nutricious4u-63158.iam.gserviceaccount.com"
    echo ""
    echo "For FIREBASE_PRIVATE_KEY, copy the entire private key from the JSON file:"
    echo "-----BEGIN PRIVATE KEY-----"
    echo "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDUnYDUWCWA7eTc"
    echo "m6LNim/X7eXcwfCmK6+Ki3G08iBsysfMkUsPlIK2Yo6LtzWGaSpca8DBypR+bO6G"
    echo "ODlFiekRlQUERBLlSuxiOUhrf9nLlTKx1tcVRg/4iy0Y4Gl0QZ4AxLaun2DH9yh0"
    echo "F6QJKv/G+/nhAeOmHj4Jye+JCeKfRmqulUwdEXqc5tQPSxAFF1r1BhNQYKdd4Zq8"
    echo "PD/ytqpeF5FB2o+6oqAdRzA4EnrnLzI5E+95tLk/sbh5U6j0bHACsLqxlarSfDeR"
    echo "fJDL10O6SppK9VcPRDZrWQPDJNhSjb157t+ZqJX/Cp5H0hJbAtIpoU68t02GW/P5"
    echo "JUS9ooGdAgMBAAECggEAGJKIdmImmXdFFUsGfo9SnEfSIlimvam8XLx/fHxkS3aH"
    echo "L2kWXftZvQb4dwTKUpm6a9qHOU52qYLg8VGzqsoEzgOlRAgzD92AIt0Ade4dh4Yb"
    echo "iQqtqneBtoWtRVwATA+eWXPish1Y49t4iSxHSMj3rTFngH4Fp6gEnwB/5txl3Obi"
    echo "HvCsuC0X0E/1ZFn7pJf/fG63q6+wSTSeFku2mE3PXFAy8/Q7H8dpefVtS9DuWp8z"
    echo "K6D4oyd07ynyf2jlhudfoEpYQYpspY4p1ava0p8NjNXfhrxxx9rdauljQvpc2i7t"
    echo "m2Kw1qB+EL77l8Z1UIRvLOasLlNdVnwk4kRSHL95kQKBgQD/BZkNEStQ9xLE3ALv"
    echo "BiME8dJ00CYOsAWSWzRYf+aT+oE/P4ERYGP1dEWGV1UwH3R+9ev9MUU9GeGqhByu"
    echo "riva/eQ50uW4VWxd5f+PSjBiNBYizgCI1lwP+xwgf2NwpwHT/c9WgXKQvFPFAJ5k"
    echo "E+y+l68aMjw2FuPYiIGQF2KaMQKBgQDVbkRXjju5eRYngg3NCYuqxgterN1n4sQn"
    echo "CZMxPS1vGRnqRpU/P/2LdbqItGVxh1UbuRvauJOUOagVAn4mxMxOFin2uLEBa3e3"
    echo "rIeX8gUbI0/99gqLx+EEkjqiYCrlgni623wTyzb8WuMdFih/sgaDmf7PNDdrxLF5"
    echo "/IrZzOMXLQKBgAtgyI9YsMIQA/pchpT7hRx3XZhwoQIOwHDjONap/jOj/ZhA0RVh"
    echo "Y5RT97Yit15KSPxRJJJLXHd5bCQbeNwiUTqYEVKzIiSzSv51gI14FeiLwmETJ9rz"
    echo "FXBxF7QrethP2zkGHfYSGHZ0sJgdivOUH//w7JMSorUXGFtU29L9+BxBAoGAIpu9"
    echo "w0DSGHI1EHT7TeslVazFfTWktUrFKdtYndxguKomVKHbY6U5tNqDQ9WUuYMLXvJ2"
    echo "PNI/RALRaY687AZvZp4bceFi+mr1v7ffSNk60Lq6JuE1tpLTvw0DKv9TFWJBt3MN"
    echo "vJvwL52BRF8qdAJnIgHfmrPJ5NTBPpmf3k9l54UCgYB+E4KDfo9Z5BEd/oZ39R/s"
    echo "oCdhnZdXpeCgQDSQH+wBwXDHnk1VqyDS2UtD6xcQLVEiXY8uKFvhSft04TMRBxAs"
    echo "9MMKKpoOHZV3v3uTPMDegjF5Wj1dnWbKuZ+O+mJpzs4LynNTzCxOnS8gYyFEjw6H"
    echo "10CkLfJA/OYvZPAoBhJyZw=="
    echo "-----END PRIVATE KEY-----"
    echo ""
    echo "Also add:"
    echo "FIREBASE_STORAGE_BUCKET=nutricious4u-diet-storage"
    echo ""
    echo "After adding these variables, redeploy your Railway project."
else
    echo "❌ Firebase service account file not found!"
    echo "Please make sure services/firebase_service_account.json exists."
fi 