services:
  - type: web
    name: nutricious4u-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDNSOV8CO_IV15t1dxokhfZShHccGF5lB0
      - key: FIREBASE_API_KEY
        value: AIzaSyAcuwyzmZlNdS47-4xjO_M74AkCwVgKPN0
      - key: FIREBASE_AUTH_DOMAIN
        value: nutricious4u-63158.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: nutricious4u-63158
      - key: FIREBASE_STORAGE_BUCKET
        value: nutricious4u-63158.firebasestorage.app
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: 383526478160
      - key: FIREBASE_APP_ID
        value: 1:383526478160:web:511c06b0bd494318068c55
      - key: FIREBASE_MEASUREMENT_ID
        value: G-BCJLVL4YGW 